version: '3.8'

services:
  # --- BACKEND ---
  backend:
    container_name: ums_backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://nhom06_admin:mricml@cluster0.plqfxwu.mongodb.net/UrbanIncidentDB?retryWrites=true&w=majority
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    networks:
      - app_network

  # --- FRONTEND ---
  frontend:
    container_name: ums_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    # --- SỬA Ở ĐÂY ---
    # Chạy yarn start và ép Vite mở host 0.0.0.0
    command: yarn start -- --host 
    # -----------------
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:
    driver: bridge